version: "3.9"

services:
  app:
    container_name: app_crud_user_knex
    build: .
    command: bash -c "npm run migrate && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db_crud_user_knex
    image: postgres:14
    volumes:
      - volume_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: psql -U ${POSTGRES_USER} ${POSTGRES_DB} || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1m

volumes:
  volume_db:
